services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    env_file:
      - backend/docker.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3020:3020"
    depends_on:
      - backend
    env_file:
      - frontend/docker.env